name: Invrentory Lite CI
on:
permissions:
  contents: read
  pull_request:
  push:
    branches: [ main ]
jobs:
 - name: Install tools
  run: |
    npm install -g htmlhint stylelint stylelint-config-standard eslint @lhci/cli

